-- =============================================================
-- BlueSPACE HR System — Supabase (PostgreSQL) Schema
-- Run this FIRST in the Supabase SQL Editor
-- =============================================================

-- Enable UUID extension (Supabase has it by default)
-- We'll use bigint for IDs to keep compatibility with existing data

-- ===================== TABLES =====================

CREATE TABLE public.branches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(191) NOT NULL,
  created_by bigint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id bigint NOT NULL DEFAULT 0,
  name varchar(191) NOT NULL,
  created_by bigint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.designations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id bigint DEFAULT NULL,
  department_id bigint NOT NULL DEFAULT 0,
  name varchar(191) NOT NULL,
  created_by bigint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(191) DEFAULT NULL,
  email varchar(191) NOT NULL UNIQUE,
  password varchar(191) DEFAULT NULL,
  type varchar(20) DEFAULT NULL,
  avatar varchar(191) NOT NULL DEFAULT 'avatar.png',
  phone varchar(191) DEFAULT NULL,
  address text DEFAULT NULL,
  is_active int NOT NULL DEFAULT 1,
  force_password_change smallint NOT NULL DEFAULT 0,
  last_login_at timestamptz DEFAULT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.employees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL DEFAULT 0,
  name varchar(191) DEFAULT NULL,
  dob date DEFAULT NULL,
  gender varchar(191) DEFAULT NULL,
  phone varchar(191) DEFAULT NULL,
  address varchar(191) DEFAULT NULL,
  next_of_kin_name varchar(191) DEFAULT NULL,
  next_of_kin_phone varchar(191) DEFAULT NULL,
  next_of_kin_relationship varchar(191) DEFAULT NULL,
  email varchar(191) DEFAULT NULL,
  password varchar(191) DEFAULT NULL,
  employee_id varchar(191) NOT NULL DEFAULT '0',
  branch_id bigint NOT NULL DEFAULT 0,
  department_id bigint NOT NULL DEFAULT 0,
  designation_id bigint NOT NULL DEFAULT 0,
  company_doj varchar(191) DEFAULT NULL,
  is_active int NOT NULL DEFAULT 1,
  created_by bigint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.leave_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(191) NOT NULL,
  days int NOT NULL,
  max_consecutive_days int DEFAULT NULL,
  requires_approval smallint NOT NULL DEFAULT 1,
  allow_carry_forward smallint NOT NULL DEFAULT 0,
  carry_forward_limit int DEFAULT NULL,
  created_by bigint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.leaves (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint NOT NULL,
  leave_type_id bigint NOT NULL,
  applied_on date NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  total_leave_days varchar(191) NOT NULL,
  leave_reason varchar(191) NOT NULL,
  remark varchar(191) DEFAULT NULL,
  status varchar(191) NOT NULL,
  half_day_type varchar(191) DEFAULT NULL,
  attachment varchar(191) DEFAULT NULL,
  created_by bigint NOT NULL DEFAULT 0,
  handover_to bigint DEFAULT NULL,
  handover_notes text DEFAULT NULL,
  contact_during_leave varchar(191) DEFAULT NULL,
  leave_address text DEFAULT NULL,
  is_half_day smallint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.holidays (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date NOT NULL,
  end_date date NOT NULL,
  occasion text NOT NULL,
  created_by bigint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  type text NOT NULL,
  data text NOT NULL,
  is_read smallint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint DEFAULT NULL,
  user_name varchar(191) DEFAULT NULL,
  user_role varchar(20) DEFAULT NULL,
  action varchar(50) NOT NULL,
  entity_type varchar(50) DEFAULT NULL,
  entity_id bigint DEFAULT NULL,
  description text NOT NULL,
  metadata jsonb DEFAULT NULL,
  ip_address varchar(45) DEFAULT NULL,
  severity varchar(10) NOT NULL DEFAULT 'INFO',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.email_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  to_email varchar(191) NOT NULL,
  subject varchar(191) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'sent',
  error_message text DEFAULT NULL,
  created_at timestamptz DEFAULT now()
);

-- ===================== INDEXES =====================

CREATE INDEX idx_audit_logs_action ON public.audit_logs (action);
CREATE INDEX idx_audit_logs_severity ON public.audit_logs (severity);
CREATE INDEX idx_audit_logs_created_at ON public.audit_logs (created_at);
CREATE INDEX idx_notifications_user_id ON public.notifications (user_id);
CREATE INDEX idx_leaves_employee_id ON public.leaves (employee_id);
CREATE INDEX idx_leaves_status ON public.leaves (status);
CREATE INDEX idx_employees_user_id ON public.employees (user_id);
CREATE INDEX idx_employees_department_id ON public.employees (department_id);

-- ===================== ROW LEVEL SECURITY =====================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.designations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.holidays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_logs ENABLE ROW LEVEL SECURITY;

-- ===================== RLS POLICIES =====================

-- Helper: check if user is management
-- We'll use a claims-based approach via auth.jwt()

-- Management can do everything
CREATE POLICY "Management full access on users"
  ON public.users FOR ALL
  USING (
    (auth.jwt() ->> 'user_role') = 'Management'
  );

CREATE POLICY "Management full access on employees"
  ON public.employees FOR ALL
  USING (
    (auth.jwt() ->> 'user_role') = 'Management'
  );

CREATE POLICY "Management full access on leaves"
  ON public.leaves FOR ALL
  USING (
    (auth.jwt() ->> 'user_role') = 'Management'
  );

CREATE POLICY "Management full access on leave_types"
  ON public.leave_types FOR ALL
  USING (
    (auth.jwt() ->> 'user_role') = 'Management'
  );

CREATE POLICY "Management full access on departments"
  ON public.departments FOR ALL
  USING (
    (auth.jwt() ->> 'user_role') = 'Management'
  );

CREATE POLICY "Management full access on designations"
  ON public.designations FOR ALL
  USING (
    (auth.jwt() ->> 'user_role') = 'Management'
  );

CREATE POLICY "Management full access on branches"
  ON public.branches FOR ALL
  USING (
    (auth.jwt() ->> 'user_role') = 'Management'
  );

CREATE POLICY "Management full access on holidays"
  ON public.holidays FOR ALL
  USING (
    (auth.jwt() ->> 'user_role') = 'Management'
  );

CREATE POLICY "Management full access on notifications"
  ON public.notifications FOR ALL
  USING (
    (auth.jwt() ->> 'user_role') = 'Management'
  );

CREATE POLICY "Management full access on audit_logs"
  ON public.audit_logs FOR ALL
  USING (
    (auth.jwt() ->> 'user_role') = 'Management'
  );

CREATE POLICY "Management full access on email_logs"
  ON public.email_logs FOR ALL
  USING (
    (auth.jwt() ->> 'user_role') = 'Management'
  );

-- Staff can read everything, but only manage their own leaves/notifications
CREATE POLICY "Staff read access on users"
  ON public.users FOR SELECT
  USING (true);

CREATE POLICY "Staff read access on employees"
  ON public.employees FOR SELECT
  USING (true);

CREATE POLICY "Staff read access on leave_types"
  ON public.leave_types FOR SELECT
  USING (true);

CREATE POLICY "Staff read access on departments"
  ON public.departments FOR SELECT
  USING (true);

CREATE POLICY "Staff read access on designations"
  ON public.designations FOR SELECT
  USING (true);

CREATE POLICY "Staff read access on branches"
  ON public.branches FOR SELECT
  USING (true);

CREATE POLICY "Staff read access on holidays"
  ON public.holidays FOR SELECT
  USING (true);

-- Staff can manage their own leaves
CREATE POLICY "Staff own leaves access"
  ON public.leaves FOR ALL
  USING (
    employee_id = ((auth.jwt() ->> 'employee_id')::bigint)
  );

-- Staff can manage their own notifications
CREATE POLICY "Staff own notifications access"
  ON public.notifications FOR ALL
  USING (
    user_id = ((auth.jwt() ->> 'sub')::bigint)
  );

-- ===================== FUNCTIONS =====================

-- Function to count working days between two dates (excluding weekends + holidays)
CREATE OR REPLACE FUNCTION public.count_working_days(start_date date, end_date date)
RETURNS int
LANGUAGE plpgsql
AS $$
DECLARE
  current_date_var date := start_date;
  count int := 0;
  holiday_dates date[];
BEGIN
  SELECT array_agg(h.date) INTO holiday_dates
  FROM public.holidays h
  WHERE h.date >= start_date AND h.date <= end_date;

  WHILE current_date_var <= end_date LOOP
    IF EXTRACT(DOW FROM current_date_var) NOT IN (0, 6) THEN
      IF holiday_dates IS NULL OR current_date_var != ALL(holiday_dates) THEN
        count := count + 1;
      END IF;
    END IF;
    current_date_var := current_date_var + INTERVAL '1 day';
  END LOOP;

  RETURN count;
END;
$$;

-- ===================== TRIGGERS =====================

-- Auto-update updated_at column
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.employees
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.leaves
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.leave_types
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.departments
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.designations
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.branches
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.holidays
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.notifications
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
